import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TodoList from "./todoList";
import dynamic from "next/dynamic";

const ReduxProvider = dynamic(() => import("@/store/redux-provider"), {
  ssr: false
});
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Redux Next App",
  description: "Generated by redux next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <TodoList />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
